In [1]:
import pandas as pd

C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
C:\Users\USER\AppData\Local\Temp\ipykernel_6428\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [4]:
df1=pd.read_csv('C:\\Users\\USER\\Downloads\\Airbnb+Data\\Airbnb Data\\Listings.csv',encoding="latin1")
autostrip=True

C:\Users\USER\AppData\Local\Temp\ipykernel_6428\1255442567.py:1: DtypeWarning: Columns (5,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df1=pd.read_csv('C:\\Users\\USER\\Downloads\\Airbnb+Data\\Airbnb Data\\Listings.csv',encoding="latin1")

In [5]:
df2=pd.read_csv("C:\\Users\\USER\\Downloads\\Airbnb+Data\\Airbnb Data\\Reviews.csv")
autostrip=True

In [6]:
df1_copy=df1.copy()

In [7]:
df2_copy=df2.copy()

In [8]:
merged_data=pd.merge(df1,df2,on="listing_id")

In [9]:
merged_data

,listing_id,name,host_id,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,review_id,date,reviewer_id
0,281420,"Beautiful Flat in le Village Montmartre, Paris",1466919,2011-12-03,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,10.0,10.0,10.0,10.0,10.0,10.0,f,173279221,2017-07-23,3501898
1,281420,"Beautiful Flat in le Village Montmartre, Paris",1466919,2011-12-03,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,10.0,10.0,10.0,10.0,10.0,10.0,f,172657766,2017-07-21,74346703
2,3705183,39 mÃÂ² Paris (Sacre CÃ âur),10328771,2013-11-29,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,10.0,10.0,10.0,10.0,10.0,10.0,f,20792760,2014-10-05,21583508
3,3705183,39 mÃÂ² Paris (Sacre CÃ âur),10328771,2013-11-29,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,10.0,10.0,10.0,10.0,10.0,10.0,f,32282670,2015-05-16,32285553
4,3705183,39 mÃÂ² Paris (Sacre CÃ âur),10328771,2013-11-29,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,10.0,10.0,10.0,10.0,10.0,10.0,f,45645391,2015-09-04,34310199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5373138,38683356,Nice and cosy mini-appartement in Paris,2238502,2012-04-27,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,10.0,10.0,10.0,10.0,10.0,10.0,f,532395580,2019-09-19,10347403
5373139,38683356,Nice and cosy mini-appartement in Paris,2238502,2012-04-27,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,10.0,10.0,10.0,10.0,10.0,10.0,f,553159713,2019-10-23,197011717
5373140,39659000,Charming apartment near Rue Saint Maur / Oberk...,38633695,2015-07-16,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,10.0,10.0,10.0,10.0,10.0,10.0,f,556350613,2019-10-29,102836346
5373141,40219504,Cosy apartment with view on Canal St Martin,6955618,2013-06-17,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,10.0,10.0,10.0,10.0,10.0,10.0,f,597833586,2020-01-26,21707358
5373142,40219504,Cosy apartment with view on Canal St Martin,6955618,2013-06-17,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,10.0,10.0,10.0,10.0,10.0,10.0,f,603384165,2020-02-09,76518059

In [10]:
missing_value_percentages=merged_data.isna().mean()*100
print("Percentage of Missing Values per Column:")
print(missing_value_percentages)

Percentage of Missing Values per Column:
listing_id                      0.000000
name                            0.006197
host_id                         0.000000
host_since                      0.073309
host_location                   0.147214
host_response_time             27.463125
host_response_rate             27.463125
host_acceptance_rate           13.929222
host_is_superhost               0.073309
host_total_listings_count       0.073309
host_has_profile_pic            0.073309
host_identity_verified          0.073309
neighbourhood                   0.000000
district                       84.222884
city                            0.000000
latitude                        0.000000
longitude                       0.000000
property_type                   0.000000
room_type                       0.000000
accommodates                    0.000000
bedrooms                       10.076281
amenities                       0.000000
price                           0.000000
minimum_nights                  0.000000
maximum_nights                  0.000000
review_scores_rating            0.113621
review_scores_accuracy          0.730727
review_scores_cleanliness       0.727154
review_scores_checkin           0.732123
review_scores_communication     0.730187
review_scores_location          0.732272
review_scores_value             0.732514
instant_bookable                0.000000
review_id                       0.000000
date                            0.000000
reviewer_id                     0.000000
dtype: float64

In [11]:
district_drop=merged_data.drop("district",axis=1)
merged_data=district_drop

In [12]:
#Drop null values in column
merged_data.dropna(subset=["host_response_rate"],inplace=True)

In [13]:
#Drop null values in column
merged_data.dropna(subset=["host_acceptance_rate"],inplace=True)

In [14]:
#drop null values in column
merged_data.dropna(subset=["host_response_time"],inplace=True)

In [15]:
#drop null values in column
merged_data.dropna(subset=["bedrooms"],inplace=True)

In [16]:
#drop null values in column
merged_data.dropna(subset=["review_scores_rating"],inplace=True)

In [17]:
#drop null values in column
merged_data.dropna(subset=["review_scores_accuracy"],inplace=True)

In [18]:
#drop null values in column
merged_data.dropna(subset=["review_scores_cleanliness"],inplace=True)

In [19]:
#drop null values in column
merged_data.dropna(subset=["review_scores_checkin"],inplace=True)

In [20]:
#drop null values in column
merged_data.dropna(subset=["review_scores_communication"],inplace=True)

In [21]:
#drop null values in column
merged_data.dropna(subset=["review_scores_location"],inplace=True)

In [22]:
#drop null values in column
merged_data.dropna(subset=["review_scores_value"],inplace=True)

In [23]:
#drop null values in column
merged_data.dropna(subset=["name"],inplace=True)

In [24]:
#drop null values in column
merged_data.dropna(subset=["host_since"],inplace=True)

In [25]:
#Rename column 
new_column={"name":"description"}
merged_data=merged_data.rename(columns=new_column)
merged_data.head()

,listing_id,description,host_id,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,review_id,date,reviewer_id
279903,39849253,Warm and Cosy Flat for 2 in Paris,305389411,2019-10-30,GB,within an hour,1.0,1.0,f,1.0,...,7.0,7.0,7.0,7.0,7.0,7.0,t,588276235,2020-01-04,3171445
279904,39849253,Warm and Cosy Flat for 2 in Paris,305389411,2019-10-30,GB,within an hour,1.0,1.0,f,1.0,...,7.0,7.0,7.0,7.0,7.0,7.0,t,604201660,2020-02-10,26071293
279905,39849253,Warm and Cosy Flat for 2 in Paris,305389411,2019-10-30,GB,within an hour,1.0,1.0,f,1.0,...,7.0,7.0,7.0,7.0,7.0,7.0,t,619003460,2020-03-16,11300816
279906,39849253,Warm and Cosy Flat for 2 in Paris,305389411,2019-10-30,GB,within an hour,1.0,1.0,f,1.0,...,7.0,7.0,7.0,7.0,7.0,7.0,t,673732789,2020-10-12,13729690
279907,40436816,Bright apartment in PIGALLE - Professional Cle...,312774780,2019-11-28,IE,within an hour,1.0,1.0,f,1.0,...,8.0,10.0,10.0,8.0,10.0,8.0,f,587547092,2020-01-03,73607333

In [27]:
merged_data["description"]

279903                     Warm and Cosy Flat for 2 in Paris
279904                     Warm and Cosy Flat for 2 in Paris
279905                     Warm and Cosy Flat for 2 in Paris
279906                     Warm and Cosy Flat for 2 in Paris
279907     Bright apartment in PIGALLE - Professional Cle...
                                 ...
5234959                   Appartement piscine place d'Italie
5234960            Cozy Montmartre flat near Le Moulin Rouge
5234961    Moderne-ancien- jungle urbaine - proche Montma...
5234962    Moderne-ancien- jungle urbaine - proche Montma...
5234963    Appartement tranquille au cÃ
âur du 5ÃÂ¨me ...
Name: description, Length: 3388769, dtype: object

In [28]:
char_replace=merged_data[~merged_data["description"].str.contains("Ã")]
merged_data=char_replace

In [30]:
merged_data["host_location"].unique()

array(['GB', 'IE', 'New York, New York, United States', ...,
       'ItaguaÃ\x83Â\xad, Rio de Janeiro, Brazil',
       'BrasÃ\x83Â\xadlia de Minas, State of Minas Gerais, Brazil',
       'istanbul/ Turkey'], dtype=object)

In [31]:
host_location_drop=merged_data.drop("host_location",axis=1)
merged_data=host_location_drop

In [32]:
missing_value_percentages=merged_data.isna().mean()*100
print("Percentage of Missing Values per Column:")
print(missing_value_percentages)

Percentage of Missing Values per Column:
listing_id                     0.0
description                    0.0
host_id                        0.0
host_since                     0.0
host_response_time             0.0
host_response_rate             0.0
host_acceptance_rate           0.0
host_is_superhost              0.0
host_total_listings_count      0.0
host_has_profile_pic           0.0
host_identity_verified         0.0
neighbourhood                  0.0
city                           0.0
latitude                       0.0
longitude                      0.0
property_type                  0.0
room_type                      0.0
accommodates                   0.0
bedrooms                       0.0
amenities                      0.0
price                          0.0
minimum_nights                 0.0
maximum_nights                 0.0
review_scores_rating           0.0
review_scores_accuracy         0.0
review_scores_cleanliness      0.0
review_scores_checkin          0.0
review_scores_communication    0.0
review_scores_location         0.0
review_scores_value            0.0
instant_bookable               0.0
review_id                      0.0
date                           0.0
reviewer_id                    0.0
dtype: float64

In [33]:
merged_data

,listing_id,description,host_id,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_has_profile_pic,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,review_id,date,reviewer_id
279903,39849253,Warm and Cosy Flat for 2 in Paris,305389411,2019-10-30,within an hour,1.0,1.0,f,1.0,t,...,7.0,7.0,7.0,7.0,7.0,7.0,t,588276235,2020-01-04,3171445
279904,39849253,Warm and Cosy Flat for 2 in Paris,305389411,2019-10-30,within an hour,1.0,1.0,f,1.0,t,...,7.0,7.0,7.0,7.0,7.0,7.0,t,604201660,2020-02-10,26071293
279905,39849253,Warm and Cosy Flat for 2 in Paris,305389411,2019-10-30,within an hour,1.0,1.0,f,1.0,t,...,7.0,7.0,7.0,7.0,7.0,7.0,t,619003460,2020-03-16,11300816
279906,39849253,Warm and Cosy Flat for 2 in Paris,305389411,2019-10-30,within an hour,1.0,1.0,f,1.0,t,...,7.0,7.0,7.0,7.0,7.0,7.0,t,673732789,2020-10-12,13729690
279907,40436816,Bright apartment in PIGALLE - Professional Cle...,312774780,2019-11-28,within an hour,1.0,1.0,f,1.0,t,...,8.0,10.0,10.0,8.0,10.0,8.0,f,587547092,2020-01-03,73607333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5234958,44273734,Charming duplex near JARDIN DU LUXEMBOURG,356893366,2020-07-17,within an hour,1.0,1.0,f,1.0,t,...,10.0,10.0,10.0,10.0,10.0,10.0,f,719657276,2020-12-30,12033233
5234959,44339814,Appartement piscine place d'Italie,3909173,2012-10-18,within a few hours,1.0,1.0,f,1.0,t,...,10.0,10.0,10.0,10.0,10.0,10.0,t,656007398,2020-08-24,56177559
5234960,45200617,Cozy Montmartre flat near Le Moulin Rouge,73974623,2016-05-25,within a day,1.0,1.0,f,1.0,t,...,10.0,10.0,10.0,10.0,10.0,10.0,f,664308160,2020-09-14,5023563
5234961,46673032,Moderne-ancien- jungle urbaine - proche Montma...,2470431,2012-05-26,within an hour,1.0,1.0,f,1.0,t,...,10.0,10.0,10.0,10.0,10.0,10.0,f,714229827,2020-12-08,103362137
5234962,46673032,Moderne-ancien- jungle urbaine - proche Montma...,2470431,2012-05-26,within an hour,1.0,1.0,f,1.0,t,...,10.0,10.0,10.0,10.0,10.0,10.0,f,718260215,2020-12-26,196763688

In [35]:
merged_data.to_csv('Python_Project.csv', index=False)

In [38]:
merged_data['price']

279903      89
279904      89
279905      89
279906      89
279907      98
          ...
5234958    159
5234959     99
5234960     80
5234961     62
5234962     62
Name: price, Length: 3079773, dtype: int64

merged_data.describe()